export const LOGIN = 'LOGIN';
export const CLEARLOGIN = 'CLEARLOGIN';
export const REGISTER = 'REGISTER';
export const PROFILE = 'PROFILE';
export const LOGOUT = 'LOGOUT';
export const UPDATEPROFILE = 'UPDATEPROFILE';
export const GETTOURISTS = 'GETTOURISTS';
export const GETDETILTOURISTS = 'GETDETILTOURISTS';
export const ADDTOURISTS = 'ADDTOURISTS';
export const UPDATETOURISTS = 'UPDATETOURISTS';
export const DELETETOURISTS = 'DELETETOURISTS';
export const CLEARDETILTOURISTS = 'CLEARDETILTOURISTS';
export const CLEARADDTOURISTS = 'CLEARADDTOURISTS';
export const CLEARUPDATETOURISTS = 'CLEARUPDATETOURISTS';
export const CLEARDELETETOURISTS = 'CLEARDELETETOURISTS';

